### ISSUE TITLE
filter() takes at least 2 arguments in "Stata ARIMA Examples"

### ISSUE THREAD

**Issue by sudodo** [ChadFulton/statsmodels#3]
On "ARIMA Postestimation: Example 1" in the following gist, I got an error message "filter() takes at least 2 arguments".
http://nbviewer.ipython.org/gist/ChadFulton/5127108f4c7025ed2648

After checking the source code, some value is needed for the argument, 'params'. According to the comment in MLEModel#filter, 'params' is used to evaluate the log likelihood.

        params : array_like
            Array of parameters at which to evaluate the loglikelihood
            function.

However, I do not get what the 'params' exactly is. What value should be given to the 'params' at the example of gist?

In advance of you answer, I'd like to appreciate your effort letting me to try SARIMA on python.

**Comment by ChadFulton** [comment]
Sorry I didn't get to this sooner - if you are still curious, please take a look at the main Statsmodels repository and documentation - e.g. statsmodels.github.io
