### ISSUE TITLE
Local level model with an exogenous variable 

### ISSUE THREAD

**Issue by sgeorg92** [ChadFulton/statsmodels#9]
Hi, 

I was working with the local level model and was wondering if it is possible to estimate the coefficient of an exogenous variable? 
Or would it make sense to transform the model into an ARMA model and use SARIMAX?

Thanks, 
Sarah

**Comment by ChadFulton** [comment]
Yes, that is possible. The `UnobservedComponents` model allows you to pass in an `exog` argument. It will then estimate the coefficient by maximum likelihood.

**Comment by sgeorg92** [comment]
Thanks so much for pointing that out!!

**Comment by ChadFulton** [comment]
Of course, no problem
